language: rust
rust: stable
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  cargo: true
addons:
  apt:
    packages:
      - mingw-w64
before_script:
  - rustup target add x86_64-unknown-linux-musl
  - rustup target add x86_64-pc-windows-gnu
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - RUSTFLAGS="-D warnings" cargo clippy
  - cargo test
  - cargo build --release --target=x86_64-unknown-linux-musl
  - strip target/x86_64-unknown-linux-musl/release/relayed
  - ls -lh target/x86_64-unknown-linux-musl/release/relayed
  - cargo build --release --target=x86_64-pc-windows-gnu
  - strip target/x86_64-pc-windows-gnu/release/relayed.exe
  - ls -lh target/x86_64-pc-windows-gnu/release/relayed.exe
deploy:
  - provider: releases
    api_key:
      secure: akNH10SJfiBgq4rmCfZWNM+HBIU0dYKlEPxvrBvqIRvbUw0Mm8NICv9M4UXSqgLgVOh9VTYx6M1RinCv2OYRpJe+sgo+jC0Th0F7cK8URK5GFiA8xUx+eIUl00TATdLFk5MmmQ3IFI9coxQEa4BwV6G35H6kNL5bYx2dQhlchghL70CTAisFjWLKzepfXu+N64r2nFQeDJvtaeQKa+uvyAtQLBsuTh+j07UhFRf2GvJ9azuNhXGeKTCMrqsHN/v3OLQecWa7D5IDj71afMApI3b6vpgdbkyrvMMF0wdcyJseNw6UN9NK0Y7QNANhOOQ/BuCQ6KChebCYAsmqT0AyfL+IwTQErZdLoT9aTWr/jlLhzGWyAA/eHhBszFnMood0LOuqhIFq7grT5x5E7zNYGaWJ1E4AoYMdloskD2SXqp5dvTi7i+/5GETO4/Hv9iYIJ2tWVn+ocSuH+VzKKSeERC65Ppc/3zV9BsgW+BeGllCgiA65SXhwM2fgbPPOuFCKOSzfSzxlEauF22XIqMCZ0bRkmRt+iEKWkZ7Eek4oZ1505WF5Uv5UZH5lrNv4SlPT7Oy4iiZ1dXxEexaaXcModlUD956u3QWEKSRdM2setb/PikAI50U0xZ9p2Eu0K+peO+7zpNVFtpV/sw1zVW1bR/KpjuxJpOntDllWDEx1QH4=
    file:
      - target/x86_64-unknown-linux-musl/release/relayed
      - target/x86_64-pc-windows-gnu/release/relayed.exe
    skip_cleanup: true
    on:
      tags: true
