[package]
name = "relayed"
version = "1.0.1"
authors = []
description = "Relay a TCP socket to a machine behind a dynamic IP/firewall."

[dependencies]
env_logger = { version = "0.6", default-features = false, features = ["humantime"] }
futures = "0.1"
log = "0.4"
structopt = { version = "0.2", default-features = false }
tokio = "0.1"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
